# Include this file from ~/.ssh/config on Phil's Mac.
Host 100.104.47.26
  User phil
  IdentityFile ~/.ssh/id_rsa
  SetEnv P10K_MAC_SSH=home

Host 217.160.186.7
  User root
  IdentityFile ~/.ssh/id_rsa
  SetEnv P10K_MAC_SSH=vps
